trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool

stages:
  - stage: deploy_stage
    displayName: terraform stage

    jobs:
      - job: deploy_job
        displayName: terraform job

        steps:
          # Install Terraform
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: "latest"

          # Terraform Init
          - task: TerraformTaskV4@4
            displayName: terraform init
            inputs:
              provider: "aws"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              environmentServiceNameAWS: "aws-connection"

          # Terraform Plan
          - task: TerraformTaskV4@4
            displayName: terraform plan
            inputs:
              provider: "aws"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              environmentServiceNameAWS: "aws-connection"

          # Terraform Apply
          - task: TerraformTaskV4@4
            displayName: terraform apply
            inputs:
              provider: "aws"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              environmentServiceNameAWS: "aws-connection"
              commandOptions: "-auto-approve"
